apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-img
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  project: default
  source:
    path: apps/
    repoURL: https://github.com/Su-HackZ/argotest.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true